### ISSUE TITLE
Test failures from Zoltan.

### ISSUE THREAD

**Issue by atgeirr** [OPM/dune-cornerpoint#148]
I get test failures now:
```
The following tests FAILED:
	  1 - distribution (Failed)
	  6 - partition_iterator (Failed)
	  7 - zoltan (Failed)
```
When running in the debugger, all failures seem to be from `Zoltan_Create()`, the call to `MPI_Comm_rank()` [line 63 of `zz_struct.c` the debugger claims].

I did notice something a little strange: `Zoltan_Create()` takes a `MPI_Comm`, but we pass a `Dune::CollectiveCommunication<MPI_Comm>`, is this correct?

I am using Open MPI on a mac, in case it matters.

**Comment by blattms** [comment]
You mean the problem occurs in calling ```MPI_Comm_rank```? That is weired. What exactly does the debugger complain about?

Passing ```Dune::CollectiveCommunication<MPI_Comm>``` should be OK as it has an automatic conversion to ```MPI_Comm```.

Unfortunately, I am unable to reproduce this using Linux.

**Comment by atgeirr** [comment]
This issue has finally been resolved: the root cause was essentially multiple installation of mpi libs. Closing the issue.

**Comment by blattms** [comment]
Cool, a bug that resolves itself. I wish all bugs would do it the same
way ;)
